# Generated by Django 4.0.4 on 2022-04-17 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='time',
        ),
        migrations.AddField(
            model_name='score',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date published'),
        ),
    ]
