# Generated by Django 4.0.4 on 2022-04-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_wordlescore_alter_score_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlescore',
            name='player_pic',
            field=models.CharField(default='0', max_length=2732),
        ),
    ]
